export type CaseStatus =
  | "BROUILLON" | "SOUMIS" | "RECU_GREFFE" | "A_VERIFIER"
  | "COMPLET" | "INCOMPLET" | "ENROLEMENT"
  | "CONCILIATION" | "CONCILIE" | "CONCILIATION_ECHEC"
  | "AUDIENCE_PLANIFIEE" | "AUDIENCE" | "DECISION_RENDUE"
  | "NOTIFIE" | "ARCHIVE";

export const transitions: Record<CaseStatus, CaseStatus[]> = {
  BROUILLON: ["SOUMIS"],
  SOUMIS: ["RECU_GREFFE"],
  RECU_GREFFE: ["A_VERIFIER"],
  A_VERIFIER: ["COMPLET", "INCOMPLET"],
  COMPLET: ["ENROLEMENT"],
  INCOMPLET: ["SOUMIS"],
  ENROLEMENT: ["CONCILIATION"],
  CONCILIATION: ["CONCILIE", "CONCILIATION_ECHEC"],
  CONCILIE: ["NOTIFIE"],
  CONCILIATION_ECHEC: ["AUDIENCE_PLANIFIEE"],
  AUDIENCE_PLANIFIEE: ["AUDIENCE"],
  AUDIENCE: ["DECISION_RENDUE"],
  DECISION_RENDUE: ["NOTIFIE"],
  NOTIFIE: ["ARCHIVE"],
  ARCHIVE: []
};

export const stageForStatus: Record<CaseStatus,string> = {
  BROUILLON:"SAISINE", SOUMIS:"SAISINE", RECU_GREFFE:"GREFFE", A_VERIFIER:"CONTROLE",
  COMPLET:"CONTROLE", INCOMPLET:"CONTROLE", ENROLEMENT:"ENROLEMENT",
  CONCILIATION:"AUDIENCES", CONCILIE:"AUDIENCES", CONCILIATION_ECHEC:"AUDIENCES",
  AUDIENCE_PLANIFIEE:"AUDIENCES", AUDIENCE:"AUDIENCES", DECISION_RENDUE:"DECISIONS",
  NOTIFIE:"NOTIFICATION", ARCHIVE:"ARCHIVAGE"
};

/**
 * Role responsable de chaque étape qui nécessite une nouvelle affectation.
 * Les autres étapes conservent automatiquement le responsable courant.
 */
export type AssignmentRole = "SAISINE"|"GREFFE"|"CONTROLE"|"ENROLEMENT"|"AUDIENCES"|"MAGISTRAT"|"NOTIFICATION"|"ARCHIVAGE";
export const assignmentRoleByStatus: Partial<Record<CaseStatus,AssignmentRole>> = {
  BROUILLON: "SAISINE",
  SOUMIS: "GREFFE",
  A_VERIFIER: "CONTROLE",
  COMPLET: "ENROLEMENT",
  ENROLEMENT: "AUDIENCES",
  CONCILIATION: "AUDIENCES",
  CONCILIE: "NOTIFICATION",
  CONCILIATION_ECHEC: "AUDIENCES",
  AUDIENCE_PLANIFIEE: "AUDIENCES",
  AUDIENCE: "AUDIENCES",
  DECISION_RENDUE: "NOTIFICATION",
  NOTIFIE: "ARCHIVAGE"
};

export const allowedRolesByTransition: Partial<Record<string,string[]>> = {
  "BROUILLON->SOUMIS":["CITOYEN","SAISINE","ADMIN"],
  "SOUMIS->RECU_GREFFE":["GREFFE","ADMIN"],
  "RECU_GREFFE->A_VERIFIER":["GREFFE","CONTROLE","ADMIN"],
  "A_VERIFIER->COMPLET":["CONTROLE","GREFFE","ADMIN"],
  "A_VERIFIER->INCOMPLET":["CONTROLE","GREFFE","ADMIN"],
  "INCOMPLET->SOUMIS":["CITOYEN","GREFFE","ADMIN"],
  "COMPLET->ENROLEMENT":["ENROLEMENT","GREFFE","ADMIN"],
  "ENROLEMENT->CONCILIATION":["AUDIENCES","GREFFE","MAGISTRAT","ADMIN"],
  "CONCILIATION->CONCILIE":["AUDIENCES","MAGISTRAT","ADMIN"],
  "CONCILIATION->CONCILIATION_ECHEC":["AUDIENCES","MAGISTRAT","ADMIN"],
  "CONCILIATION_ECHEC->AUDIENCE_PLANIFIEE":["AUDIENCES","MAGISTRAT","ADMIN"],
  "AUDIENCE_PLANIFIEE->AUDIENCE":["AUDIENCES","MAGISTRAT","ADMIN"],
  "AUDIENCE->DECISION_RENDUE":["MAGISTRAT","AUDIENCES","ADMIN"],
  "DECISION_RENDUE->NOTIFIE":["NOTIFICATION","GREFFE","MAGISTRAT","ADMIN"],
  "NOTIFIE->ARCHIVE":["ARCHIVAGE","GREFFE","ADMIN"]
};

export function canTransition(from: CaseStatus, to: CaseStatus): boolean {
  return transitions[from]?.includes(to) ?? false;
}
