export type CaseStatus =
  | "BROUILLON" | "SOUMIS" | "RECU_GREFFE" | "A_VERIFIER"
  | "COMPLET" | "INCOMPLET" | "ENROLEMENT"
  | "CONCILIATION" | "CONCILIE" | "CONCILIATION_ECHEC"
  | "AUDIENCE_PLANIFIEE" | "AUDIENCE" | "DECISION_RENDUE"
  | "NOTIFIE" | "ARCHIVE";

export const transitions: Record<CaseStatus, CaseStatus[]> = {
  BROUILLON: ["SOUMIS"],
  SOUMIS: ["RECU_GREFFE"],
  RECU_GREFFE: ["A_VERIFIER"],
  A_VERIFIER: ["COMPLET", "INCOMPLET"],
  COMPLET: ["ENROLEMENT"],
  INCOMPLET: ["SOUMIS"],
  ENROLEMENT: ["CONCILIATION"],
  CONCILIATION: ["CONCILIE", "CONCILIATION_ECHEC"],
  CONCILIE: ["NOTIFIE"],
  CONCILIATION_ECHEC: ["AUDIENCE_PLANIFIEE"],
  AUDIENCE_PLANIFIEE: ["AUDIENCE"],
  AUDIENCE: ["DECISION_RENDUE"],
  DECISION_RENDUE: ["NOTIFIE"],
  NOTIFIE: ["ARCHIVE"],
  ARCHIVE: []
};

export const stageForStatus: Record<CaseStatus,string> = {
  BROUILLON:"SAISINE", SOUMIS:"SAISINE", RECU_GREFFE:"GREFFE", A_VERIFIER:"CONTROLE",
  COMPLET:"CONTROLE", INCOMPLET:"CONTROLE", ENROLEMENT:"ENROLEMENT",
  CONCILIATION:"AUDIENCES", CONCILIE:"AUDIENCES", CONCILIATION_ECHEC:"AUDIENCES",
  AUDIENCE_PLANIFIEE:"AUDIENCES", AUDIENCE:"AUDIENCES", DECISION_RENDUE:"DECISIONS",
  NOTIFIE:"NOTIFICATION", ARCHIVE:"ARCHIVAGE"
};

/**
 * Role responsable de chaque étape qui nécessite une nouvelle affectation.
 * Les autres étapes conservent automatiquement le responsable courant.
 */
export const assignmentRoleByStatus: Partial<Record<CaseStatus,"GREFFE"|"MAGISTRAT">> = {
  SOUMIS: "GREFFE",
  ENROLEMENT: "GREFFE",
  NOTIFIE: "GREFFE"
};

export const allowedRolesByTransition: Partial<Record<string,string[]>> = {
  "BROUILLON->SOUMIS":["CITOYEN"],
  "SOUMIS->RECU_GREFFE":["GREFFE","ADMIN"],
  "RECU_GREFFE->A_VERIFIER":["GREFFE","ADMIN"],
  "A_VERIFIER->COMPLET":["GREFFE","ADMIN"],
  "A_VERIFIER->INCOMPLET":["GREFFE","ADMIN"],
  "INCOMPLET->SOUMIS":["CITOYEN","GREFFE","ADMIN"],
  "COMPLET->ENROLEMENT":["GREFFE","ADMIN"],
  "ENROLEMENT->CONCILIATION":["GREFFE","MAGISTRAT","ADMIN"],
  "CONCILIATION->CONCILIE":["GREFFE","MAGISTRAT","ADMIN"],
  "CONCILIATION->CONCILIATION_ECHEC":["GREFFE","MAGISTRAT","ADMIN"],
  "CONCILIE->NOTIFIE":["GREFFE","ADMIN"],
  "CONCILIATION_ECHEC->AUDIENCE_PLANIFIEE":["GREFFE","MAGISTRAT","ADMIN"],
  "AUDIENCE_PLANIFIEE->AUDIENCE":["GREFFE","MAGISTRAT","ADMIN"],
  "AUDIENCE->DECISION_RENDUE":["MAGISTRAT","ADMIN"],
  "DECISION_RENDUE->NOTIFIE":["GREFFE","MAGISTRAT","ADMIN"],
  "NOTIFIE->ARCHIVE":["GREFFE","ADMIN"]
};

export function canTransition(from: CaseStatus, to: CaseStatus): boolean {
  return transitions[from]?.includes(to) ?? false;
}
