import React,{useEffect,useMemo,useState} from "react";
import {createRoot} from "react-dom/client";
import {getDashboard,getCases,getCalendar,getNotifications,login,searchDocuments,createCase,uploadDocument,transitionCase,getCaseParties,addParty,getCaseDocuments,getHearings,createHearing,getConciliations,createConciliation,updateConciliation,getDecisions,createDecision,getAudit,getUsers,updateUserAccess,searchLegalSources,legalAssist} from "./api";
import "./styles.css";

type Case={id:string;reference:string;title:string;status:string;claimant_id?:string};
const statuses=["BROUILLON","SOUMIS","RECU_GREFFE","A_VERIFIER","COMPLET","INCOMPLET","CONCILIATION","AUDIENCE_PLANIFIEE","AUDIENCE","DECISION_RENDUE","NOTIFIE","ARCHIVE"];
const nextMap:Record<string,string[]>={BROUILLON:["SOUMIS"],SOUMIS:["RECU_GREFFE"],RECU_GREFFE:["A_VERIFIER"],A_VERIFIER:["COMPLET","INCOMPLET"],COMPLET:["CONCILIATION"],INCOMPLET:["SOUMIS"],CONCILIATION:["AUDIENCE_PLANIFIEE","DECISION_RENDUE"],AUDIENCE_PLANIFIEE:["AUDIENCE"],AUDIENCE:["DECISION_RENDUE"],DECISION_RENDUE:["NOTIFIE"],NOTIFIE:["ARCHIVE"],ARCHIVE:[]};

function Login({onLogin}:{onLogin:()=>void}){const[e,setE]=useState("");const[p,setP]=useState("");const[err,setErr]=useState("");async function go(){try{await login(e,p);onLogin()}catch(x:any){setErr(x.message)}}return <main className="login"><div className="loginCard"><span className="mark">eT</span><h1>e-Travail</h1><p>Plateforme numérique de gestion des dossiers de travail</p><input placeholder="Email" value={e} onChange={x=>setE(x.target.value)}/><input type="password" placeholder="Mot de passe" value={p} onChange={x=>setP(x.target.value)}/><button onClick={go}>Se connecter</button>{err&&<p className="error">{err}</p>}</div></main>}

function CaseDetail({c,userRole,onClose,onRefresh,onError}:{c:Case;userRole:string;onClose:()=>void;onRefresh:()=>void;onError:(x:string)=>void}){
 const[parties,setParties]=useState<any[]>([]),[docs,setDocs]=useState<any[]>([]),[hearings,setHearings]=useState<any[]>([]),[conc,setConc]=useState<any[]>([]),[dec,setDec]=useState<any[]>([]),[audit,setAudit]=useState<any[]>([]);
 const[busy,setBusy]=useState(false),[party,setParty]=useState({type:"SALARIE",fullName:"",contact:""}),[file,setFile]=useState<File|null>(null);
 const[date,setDate]=useState(""),[room,setRoom]=useState(""),[notes,setNotes]=useState(""),[decision,setDecision]=useState(""),[decisionRef,setDecisionRef]=useState("");
 async function load(){try{const [p,d,h,co,de,a]=await Promise.all([getCaseParties(c.id),getCaseDocuments(c.id),getHearings(c.id),getConciliations(c.id),getDecisions(c.id),userRole==="CITOYEN"?Promise.resolve({data:[]}):getAudit(c.id)]);setParties(p.data??[]);setDocs(d.data??[]);setHearings(h.data??[]);setConc(co.data??[]);setDec(de.data??[]);setAudit(a.data??[])}catch(e:any){onError(e.message)}}
 useEffect(()=>{load()},[c.id]);
 async function act(fn:()=>Promise<any>){try{setBusy(true);await fn();await load();onRefresh()}catch(e:any){onError(e.message)}finally{setBusy(false)}}
 const staff=userRole!=="CITOYEN";
 return <section className="detail"><div className="detailHead"><div><span className="eyebrow">DOSSIER {c.reference}</span><h2>{c.title}</h2><span className="pill">{c.status}</span></div><button onClick={onClose}>Fermer</button></div>
 <div className="workflow">{statuses.map((s,i)=><span className={s===c.status?"active":statuses.indexOf(c.status)>i?"done":""} key={s}>{s.replaceAll("_"," ")}</span>)}</div>
 {staff&&<div className="actionGrid"><div className="panel"><h3>Workflow</h3><p>Étape actuelle : <b>{c.status}</b></p><div className="buttonRow">{(nextMap[c.status]??[]).map(n=><button disabled={busy} key={n} onClick={()=>act(()=>transitionCase(c.id,n))}>→ {n.replaceAll("_"," ")}</button>)}</div></div>
 <div className="panel"><h3>Programmer</h3><input type="datetime-local" value={date} onChange={e=>setDate(e.target.value)}/><input placeholder="Salle" value={room} onChange={e=>setRoom(e.target.value)}/><div className="buttonRow"><button disabled={busy||!date} onClick={()=>act(()=>createConciliation(c.id,{scheduledAt:new Date(date).toISOString(),room,notes}))}>Conciliation</button><button disabled={busy||!date} onClick={()=>act(()=>createHearing(c.id,{scheduledAt:new Date(date).toISOString(),room}))}>Audience</button></div></div></div>}
 <div className="detailGrid"><div className="panel"><h3>Parties</h3>{parties.map(x=><div className="row" key={x.id}><b>{x.full_name}</b><span>{x.type} · {x.contact||"—"}</span></div>)}{staff&&<><select value={party.type} onChange={e=>setParty({...party,type:e.target.value})}><option>SALARIE</option><option>EMPLOYEUR</option><option>AUTRE</option></select><input placeholder="Nom complet" value={party.fullName} onChange={e=>setParty({...party,fullName:e.target.value})}/><input placeholder="Contact" value={party.contact} onChange={e=>setParty({...party,contact:e.target.value})}/><button onClick={()=>act(()=>addParty(c.id,party))}>Ajouter la partie</button></>}</div>
 <div className="panel"><h3>Pièces & OCR</h3>{docs.map(x=><div className="row" key={x.id}><b>{x.filename}</b><span>{x.mime_type} · {x.file_size} octets</span><a href={`#download-${x.id}`} onClick={e=>{e.preventDefault();const t=localStorage.getItem("etravail_token");fetch((import.meta.env.VITE_API_URL??"")+`/cases/${c.id}/documents/${x.id}/download`,{headers:{Authorization:`Bearer ${t}`}}).then(r=>r.blob()).then(b=>{const u=URL.createObjectURL(b);const a=document.createElement("a");a.href=u;a.download=x.filename;a.click();URL.revokeObjectURL(u)})}}>Télécharger</a>{x.ocr_text&&<small>{x.ocr_text.slice(0,180)}…</small>}</div>)}<label className="upload">Déposer une pièce<input type="file" accept=".pdf,image/jpeg,image/png" onChange={e=>setFile(e.target.files?.[0]??null)}/></label>{file&&<button disabled={busy} onClick={()=>act(()=>uploadDocument(c.id,file).then(()=>setFile(null)))}>Envoyer {file.name}</button>}</div>
 <div className="panel"><h3>Conciliations</h3>{conc.map(x=><div className="row" key={x.id}><b>{new Date(x.scheduled_at).toLocaleString("fr-FR")}</b><span>{x.room||"Salle —"} · {x.status}</span>{staff&&<div className="buttonRow">{["EN_COURS","ACCORD","ECHEC","ANNULEE"].map(s=><button key={s} onClick={()=>act(()=>updateConciliation(x.id,s,notes))}>{s}</button>)}</div>}</div>)}{staff&&<textarea placeholder="Note de conciliation" value={notes} onChange={e=>setNotes(e.target.value)}/>}</div>
 <div className="panel"><h3>Audiences</h3>{hearings.map(x=><div className="row" key={x.id}><b>{new Date(x.scheduled_at).toLocaleString("fr-FR")}</b><span>{x.room||"Salle —"} · {x.status}</span></div>)}</div>
 <div className="panel"><h3>Décisions</h3>{dec.map(x=><div className="row" key={x.id}><b>{x.decision_reference||"Décision"}</b><span>{new Date(x.created_at).toLocaleString("fr-FR")}</span><p>{x.content}</p></div>)}{userRole==="MAGISTRAT"||userRole==="ADMIN"?<><input placeholder="Référence décision" value={decisionRef} onChange={e=>setDecisionRef(e.target.value)}/><textarea placeholder="Contenu de la décision" value={decision} onChange={e=>setDecision(e.target.value)}/><button disabled={busy||decision.trim().length<10} onClick={()=>act(()=>createDecision(c.id,{reference:decisionRef,content:decision}))}>Enregistrer la décision</button></>:null}</div>
 {staff&&<div className="panel"><h3>Journal d'audit</h3>{audit.map(x=><div className="row" key={x.id}><b>{x.action}</b><span>{new Date(x.created_at).toLocaleString("fr-FR")} · {x.actor_name||x.actor_id}</span><small>{JSON.stringify(x.metadata||{})}</small></div>)}</div>}
 </div></section>
}

function App(){const[ready,setReady]=useState(!!localStorage.getItem("etravail_token"));const[dashboard,setDashboard]=useState<any>(null),[cases,setCases]=useState<Case[]>([]),[calendar,setCalendar]=useState<any[]>([]),[notifications,setNotifications]=useState<any[]>([]),[query,setQuery]=useState(""),[results,setResults]=useState<any[]>([]),[legalQuery,setLegalQuery]=useState(""),[legalResults,setLegalResults]=useState<any[]>([]),[aiQuestion,setAiQuestion]=useState(""),[aiAnswer,setAiAnswer]=useState<any>(null),[error,setError]=useState(""),[selected,setSelected]=useState<Case|null>(null),[busy,setBusy]=useState(false),[users,setUsers]=useState<any[]>([]);const user=JSON.parse(localStorage.getItem("etravail_user")||'{"role":"VISITEUR"}');
 async function load(){try{const[d,c,cal,n]=await Promise.all([getDashboard(),getCases(),getCalendar(),getNotifications()]);setDashboard(d.data);setCases(c.data??[]);setCalendar(cal.data??[]);setNotifications(n.data??[]);if(user.role==="ADMIN"){try{setUsers((await getUsers()).data??[])}catch{}}}catch(e:any){setError(e.message)}}
 useEffect(()=>{if(ready)load()},[ready]);
 async function search(){try{setResults((await searchDocuments(query)).data??[])}catch(e:any){setError(e.message)}}
 async function submit(c:Case){try{setBusy(true);await transitionCase(c.id,"SOUMIS");await load()}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 function logout(){localStorage.removeItem("etravail_token");localStorage.removeItem("etravail_user");setReady(false)}
 if(!ready)return <Login onLogin={()=>setReady(true)}/>;
 return <main className="shell"><header><div className="brand"><span className="mark">eT</span><div><strong>e-Travail</strong><small>Gestion numérique des dossiers de travail</small></div></div><div><span className="role">{user.role}</span><button onClick={logout}>Déconnexion</button></div></header>
 <section className="hero"><div><span className="eyebrow">TABLEAU DE BORD</span><h1>Gestion numérique des dossiers de travail.</h1><p>Saisine, greffe, contrôle, conciliation, audience, décision, notification et archivage.</p></div><div className="card"><span>DOSSIERS</span><strong>{cases.length}</strong><i>{dashboard?.upcomingHearings??0} audience(s) à venir</i></div></section>
 {user.role==="CITOYEN"&&<section className="rolePanel"><div><span className="eyebrow dark">ESPACE CITOYEN</span><h2>Mes démarches</h2><p>Créer un dossier, déposer des pièces et suivre son traitement.</p></div><div className="actionBox"><div className="formRow"><input id="newTitle" placeholder="Objet de la demande"/><button onClick={async()=>{const el=document.getElementById("newTitle") as HTMLInputElement;if(!el.value.trim())return;try{const d=await createCase(el.value.trim());setCases(x=>[d.data,...x]);el.value=""}catch(e:any){setError(e.message)}}}>Créer le dossier</button></div></div></section>}
 <div className="stats"><article><small>NOTIFICATIONS</small><strong>{notifications.length}</strong></article><article><small>ÉVÉNEMENTS À VENIR</small><strong>{calendar.length}</strong></article><article><small>RÔLE</small><strong>{user.role}</strong></article></div>
 {error&&<div className="alert">{error}<button onClick={()=>setError("")}>×</button></div>}
 {selected?<CaseDetail c={selected} userRole={user.role} onClose={()=>setSelected(null)} onRefresh={load} onError={setError}/>:<>
 <section className="sectionHead"><div><div><h2>Dossiers</h2><p className="muted">Cliquez sur un dossier pour ouvrir son espace opérationnel.</p></div></div>{user.role!=="CITOYEN"&&<div className="search"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Recherche OCR"/><button onClick={search}>Rechercher</button></div>}</section>
 {results.length>0&&<section className="results">{results.map(r=><article key={r.id}><b>{r.filename}</b><p>{r.excerpt}</p></article>)}</section>}
 <div className="grid">{cases.map(c=><article key={c.id} className="caseCard" onClick={()=>setSelected(c)}><small>{c.reference}</small><h3>{c.title}</h3><p className="status">{c.status.replaceAll("_"," ")}</p>{user.role==="CITOYEN"&&c.status==="BROUILLON"&&<button disabled={busy} onClick={e=>{e.stopPropagation();submit(c)}}>Soumettre</button>}</article>)}</div>
 <section><h2>Calendrier opérationnel</h2><div className="grid">{calendar.slice(0,8).map(x=><article key={x.type+x.id}><small>{x.type}</small><h3>{new Date(x.scheduled_at).toLocaleString("fr-FR")}</h3><p>{x.room||"Salle non renseignée"} · {x.status}</p></article>)}</div></section>
 <section><h2>Notifications</h2><div className="results">{notifications.slice(0,8).map(n=><article key={n.id}><b>{n.subject}</b><p>{n.body}</p></article>)}</div></section><section><h2>Recherche juridique & assistance</h2><div className="actionBox"><div className="formRow"><input value={legalQuery} onChange={e=>setLegalQuery(e.target.value)} placeholder="Article, licenciement, salaire, conciliation…"/><button onClick={async()=>{try{setLegalResults((await searchLegalSources(legalQuery)).data??[])}catch(e:any){setError(e.message)}}}>Rechercher</button></div><div className="formRow"><input value={aiQuestion} onChange={e=>setAiQuestion(e.target.value)} placeholder="Poser une question juridique à l'assistant"/><button onClick={async()=>{try{setAiAnswer((await legalAssist(aiQuestion)).data)}catch(e:any){setError(e.message)}}}>Assister</button></div></div>{aiAnswer&&<article className="results"><b>Assistance — {aiAnswer.model}</b><p>{aiAnswer.answer}</p></article>}<div className="results">{legalResults.map(r=><article key={r.id}><b>{r.title}</b><small>{r.source_type} · {r.version_label||"Version non renseignée"}</small><p dangerouslySetInnerHTML={{__html:r.excerpt||""}}></p>{r.official_url&&<a href={r.official_url} target="_blank" rel="noreferrer">Source officielle</a>}</article>)}</div></section>
 {user.role==="ADMIN"&&<section><h2>Administration — utilisateurs</h2><div className="grid">{users.map(u=><article key={u.id}><b>{u.full_name||u.email}</b><p>{u.email}</p><div className="buttonRow"><select defaultValue={u.role} onChange={async e=>{try{await updateUserAccess(u.id,{role:e.target.value,active:u.active});setUsers(x=>x.map(z=>z.id===u.id?{...z,role:e.target.value}:z))}catch(e:any){setError(e.message)}}}><option>CITOYEN</option><option>GREFFE</option><option>MAGISTRAT</option><option>ADMIN</option></select><button onClick={async()=>{try{const active=!u.active;await updateUserAccess(u.id,{role:u.role,active});setUsers(x=>x.map(z=>z.id===u.id?{...z,active}:z))}catch(e:any){setError(e.message)}}}>{u.active?"Désactiver":"Activer"}</button></div><span className="pill">{u.role}</span><small>{u.active?"Actif":"Inactif"}</small></article>)}</div></section>}
 </>}
 <footer>e-Travail — plateforme numérique de gestion et de suivi. Elle ne constitue pas un tribunal.</footer></main>}
createRoot(document.getElementById("root")!).render(<React.StrictMode><App/></React.StrictMode>);
