import React,{useEffect,useState} from "react";
import {createRoot} from "react-dom/client";
import {getDashboard,getCases,getCalendar,getNotifications,login,searchDocuments,createCase,uploadDocument,transitionCase} from "./api";
import "./styles.css";

type Case={id:string;reference:string;title:string;status:string};
function Login({onLogin}:{onLogin:()=>void}){const[e,setE]=useState("");const[p,setP]=useState("");const[err,setErr]=useState("");async function go(){try{await login(e,p);onLogin()}catch(x:any){setErr(x.message)}}return <main className="login"><div className="loginCard"><span className="mark">eT</span><h1>e-Travail</h1><p>Connexion à la plateforme</p><input placeholder="Email" value={e} onChange={x=>setE(x.target.value)}/><input type="password" placeholder="Mot de passe" value={p} onChange={x=>setP(x.target.value)}/><button onClick={go}>Se connecter</button>{err&&<p className="error">{err}</p>}</div></main>}

function RolePanel({role,onCreated,onError}:{role:string;onCreated:(c:Case)=>void;onError:(e:string)=>void}){
 const[title,setTitle]=useState(""); const[file,setFile]=useState<File|null>(null); const[selected,setSelected]=useState("");
 async function submitCase(){try{if(!title.trim())return;const d=await createCase(title.trim());onCreated(d.data);setTitle("")}catch(e:any){onError(e.message)}}
 return <section className="rolePanel"><div><span className="eyebrow dark">ESPACE {role}</span><h2>{role==="CITOYEN"?"Mes démarches":"Pilotage des dossiers"}</h2><p>{role==="CITOYEN"?"Créer un dossier, déposer des pièces et suivre les étapes de traitement.":"Suivre les dossiers, leur workflow et les événements opérationnels selon vos habilitations."}</p></div>{role==="CITOYEN"&&<div className="actionBox"><h3>Nouveau dossier</h3><div className="formRow"><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Objet de la demande"/><button onClick={submitCase}>Créer le dossier</button></div><small>Le dossier est créé au statut BROUILLON.</small></div>}{role!=="CITOYEN"&&<div className="roleChecklist"><span>✓ Accès aux dossiers</span><span>✓ Suivi du workflow</span><span>✓ Traçabilité et audit</span>{role==="GREFFE"&&<span>✓ Gestion des audiences</span>}{role==="MAGISTRAT"&&<span>✓ Préparation des décisions</span>}{role==="ADMIN"&&<span>✓ Administration</span>}</div>}</section>
}

function App(){const[ready,setReady]=useState(!!localStorage.getItem("etravail_token"));const[dashboard,setDashboard]=useState<any>(null),[cases,setCases]=useState<Case[]>([]),[calendar,setCalendar]=useState<any[]>([]),[notifications,setNotifications]=useState<any[]>([]),[query,setQuery]=useState(""),[results,setResults]=useState<any[]>([]),[error,setError]=useState(""),[busy,setBusy]=useState(false);const user=JSON.parse(localStorage.getItem("etravail_user")||'{"role":"VISITEUR"}');
 async function load(){try{const[d,c,cal,n]=await Promise.all([getDashboard(),getCases(),getCalendar(),getNotifications()]);setDashboard(d.data);setCases(c.data??[]);setCalendar(cal.data??[]);setNotifications(n.data??[])}catch(e:any){setError(e.message)}}
 useEffect(()=>{if(ready)load()},[ready]);
 async function search(){try{setResults((await searchDocuments(query)).data??[])}catch(e:any){setError(e.message)}}
 async function advance(c:Case){const next=c.status==="BROUILLON"?"SOUMIS":c.status==="INCOMPLET"?"SOUMIS":"";if(!next)return;try{setBusy(true);await transitionCase(c.id,next);await load()}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 async function upload(c:Case){if(!file)return;try{setBusy(true);await uploadDocument(c.id,file);setFile(null);setSelected("")}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 function logout(){localStorage.removeItem("etravail_token");localStorage.removeItem("etravail_user");setReady(false)}
 if(!ready)return <Login onLogin={()=>setReady(true)}/>;
 return <main className="shell"><header><div className="brand"><span className="mark">eT</span><div><strong>e-Travail</strong><small>Gestion numérique des dossiers de travail</small></div></div><div><span className="role">{user.role}</span><button onClick={logout}>Déconnexion</button></div></header>
 <section className="hero"><div><span className="eyebrow">TABLEAU DE BORD</span><h1>Suivi numérique des dossiers de travail.</h1><p>Workflow, pièces, OCR, conciliations, audiences, notifications et traçabilité.</p></div><div className="card"><span>DOSSIERS</span><strong>{cases.length}</strong><i>{dashboard?.upcomingHearings??0} audience(s) à venir</i></div></section>
 <RolePanel role={user.role} onCreated={c=>{setCases(x=>[c,...x]);setError("")}} onError={setError}/>
 <div className="stats"><article><small>NOTIFICATIONS</small><strong>{notifications.length}</strong></article><article><small>ÉVÉNEMENTS À VENIR</small><strong>{calendar.length}</strong></article><article><small>RÔLE</small><strong>{user.role}</strong></article></div>
 <section><h2>Recherche documentaire OCR</h2><div className="search"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Rechercher dans les pièces"/><button onClick={search}>Rechercher</button></div>{error&&<p className="error">{error}</p>}<div className="results">{results.map(r=><article key={r.id}><b>{r.filename}</b><p>{r.excerpt}</p></article>)}</div></section>
 <section><h2>Dossiers</h2><div className="grid">{cases.map(c=><article key={c.id}><small>{c.reference}</small><h3>{c.title}</h3><p className="status">{c.status}</p>{(user.role==="CITOYEN"&&c.status==="BROUILLON")&&<button disabled={busy} onClick={()=>advance(c)}>Soumettre</button>}{user.role==="CITOYEN"&&<label className="upload">Déposer une pièce<input type="file" accept=".pdf,image/jpeg,image/png" onChange={e=>{setSelected(c.id);setFile(e.target.files?.[0]??null)}}/></label>}{selected===c.id&&file&&<button disabled={busy} onClick={()=>upload(c)}>Envoyer {file.name}</button>}</article>)}</div></section>
 <section><h2>Calendrier</h2><div className="grid">{calendar.slice(0,6).map(x=><article key={x.type+x.id}><small>{x.type}</small><h3>{new Date(x.scheduled_at).toLocaleString("fr-FR")}</h3><p>{x.room||"Salle non renseignée"} · {x.status}</p></article>)}</div></section>
 <section><h2>Notifications récentes</h2><div className="results">{notifications.slice(0,6).map(n=><article key={n.id}><b>{n.subject}</b><p>{n.body}</p></article>)}</div></section>
 <footer>e-Travail — plateforme numérique de gestion et de suivi. Elle ne constitue pas un tribunal.</footer></main>}
createRoot(document.getElementById("root")!).render(<React.StrictMode><App/></React.StrictMode>);
